site_name: Wikistats template

use_directory_urls: false

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


nav:
  - Course: metamodeling.md
  - Ressource: ressource
  - Github repository: https://github.com/wikistat/Computer-experiments
#theme: slate
theme:
  name: 'flatly'
  logo: img/logo-insa.jpg
  favicon: img/favicon.ico


